version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.5.1
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      node.name: es01
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      cluster.name: elasticsearch
      xpack.security.enabled: false
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    networks:
      - elasticnet
  
  kibana:
    image: kibana:8.5.1
    container_name: kibana
    ports:
      - '5601:5601'
      - '9600:9600'
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      XPACK_SECURITY_ENABLED: false
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

  python-server:
    build: modules
    container_name: python-server
    ports:
      - '9560:9560'
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

volumes:
  logvolume01:

networks:
  elasticnet:

